import Head from 'next/head'

function Home(){
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Hello World</h1>
      </div>
    </>
  )
}

export default Home
